---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3338372712-n5QIPoHlfnZQzsEv4q1rQxDPQ7ac2ruiZyazcaI
:access_token_secret: 3UgmpABts2ZR0CXTtCmZYc67qm2OjPFhPqLUGtRl42uFY
